# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cefbb0b37df81f77b59f6be0dce8b2494609fdea8793de5453c0e0f0a04f12da603c726957f221b5f42ea776e4cadd30bdc4b0ca53e93de99c90a34831d3556

test:
  secret_key_base: ceca184580561a4e860fbfedf38ce7ab1307c16b2919e36347795a08ab8a85503ca6529ed5d414dd00f4bb8e6126454f61755fd09ba5f55c583f26639ce8e2c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
